// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/johnny-morrice/godless (interfaces: NamespaceTree,NamespaceTreeTableReader)

package mock_godless

import (
	gomock "github.com/golang/mock/gomock"
	godless "github.com/johnny-morrice/godless"
)

// Mock of NamespaceTree interface
type MockNamespaceTree struct {
	ctrl     *gomock.Controller
	recorder *_MockNamespaceTreeRecorder
}

// Recorder for MockNamespaceTree (not exported)
type _MockNamespaceTreeRecorder struct {
	mock *MockNamespaceTree
}

func NewMockNamespaceTree(ctrl *gomock.Controller) *MockNamespaceTree {
	mock := &MockNamespaceTree{ctrl: ctrl}
	mock.recorder = &_MockNamespaceTreeRecorder{mock}
	return mock
}

func (_m *MockNamespaceTree) EXPECT() *_MockNamespaceTreeRecorder {
	return _m.recorder
}

func (_m *MockNamespaceTree) JoinTable(_param0 string, _param1 godless.Table) error {
	ret := _m.ctrl.Call(_m, "JoinTable", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockNamespaceTreeRecorder) JoinTable(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "JoinTable", arg0, arg1)
}

func (_m *MockNamespaceTree) LoadTraverse(_param0 godless.NamespaceTreeTableReader) error {
	ret := _m.ctrl.Call(_m, "LoadTraverse", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockNamespaceTreeRecorder) LoadTraverse(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LoadTraverse", arg0)
}

// Mock of NamespaceTreeTableReader interface
type MockNamespaceTreeTableReader struct {
	ctrl     *gomock.Controller
	recorder *_MockNamespaceTreeTableReaderRecorder
}

// Recorder for MockNamespaceTreeTableReader (not exported)
type _MockNamespaceTreeTableReaderRecorder struct {
	mock *MockNamespaceTreeTableReader
}

func NewMockNamespaceTreeTableReader(ctrl *gomock.Controller) *MockNamespaceTreeTableReader {
	mock := &MockNamespaceTreeTableReader{ctrl: ctrl}
	mock.recorder = &_MockNamespaceTreeTableReaderRecorder{mock}
	return mock
}

func (_m *MockNamespaceTreeTableReader) EXPECT() *_MockNamespaceTreeTableReaderRecorder {
	return _m.recorder
}

func (_m *MockNamespaceTreeTableReader) ReadNamespace(_param0 godless.Namespace) (bool, error) {
	ret := _m.ctrl.Call(_m, "ReadNamespace", _param0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockNamespaceTreeTableReaderRecorder) ReadNamespace(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ReadNamespace", arg0)
}

func (_m *MockNamespaceTreeTableReader) ReadsTables() []string {
	ret := _m.ctrl.Call(_m, "ReadsTables")
	ret0, _ := ret[0].([]string)
	return ret0
}

func (_mr *_MockNamespaceTreeTableReaderRecorder) ReadsTables() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ReadsTables")
}
