// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/johnny-morrice/godless/api (interfaces: KvNamespace,RemoteStore,NamespaceTree,NamespaceTreeTableReader)

package mock_godless

import (
	gomock "github.com/golang/mock/gomock"
	api "github.com/johnny-morrice/godless/api"
	crdt "github.com/johnny-morrice/godless/crdt"
	query "github.com/johnny-morrice/godless/query"
)

// Mock of KvNamespace interface
type MockKvNamespace struct {
	ctrl     *gomock.Controller
	recorder *_MockKvNamespaceRecorder
}

// Recorder for MockKvNamespace (not exported)
type _MockKvNamespaceRecorder struct {
	mock *MockKvNamespace
}

func NewMockKvNamespace(ctrl *gomock.Controller) *MockKvNamespace {
	mock := &MockKvNamespace{ctrl: ctrl}
	mock.recorder = &_MockKvNamespaceRecorder{mock}
	return mock
}

func (_m *MockKvNamespace) EXPECT() *_MockKvNamespaceRecorder {
	return _m.recorder
}

func (_m *MockKvNamespace) IsChanged() bool {
	ret := _m.ctrl.Call(_m, "IsChanged")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockKvNamespaceRecorder) IsChanged() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IsChanged")
}

func (_m *MockKvNamespace) Persist() (api.KvNamespace, error) {
	ret := _m.ctrl.Call(_m, "Persist")
	ret0, _ := ret[0].(api.KvNamespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockKvNamespaceRecorder) Persist() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Persist")
}

func (_m *MockKvNamespace) Replicate(_param0 crdt.RemoteStoreAddress, _param1 api.KvQuery) {
	_m.ctrl.Call(_m, "Replicate", _param0, _param1)
}

func (_mr *_MockKvNamespaceRecorder) Replicate(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Replicate", arg0, arg1)
}

func (_m *MockKvNamespace) Reset() {
	_m.ctrl.Call(_m, "Reset")
}

func (_mr *_MockKvNamespaceRecorder) Reset() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Reset")
}

func (_m *MockKvNamespace) RunKvQuery(_param0 *query.Query, _param1 api.KvQuery) {
	_m.ctrl.Call(_m, "RunKvQuery", _param0, _param1)
}

func (_mr *_MockKvNamespaceRecorder) RunKvQuery(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RunKvQuery", arg0, arg1)
}

func (_m *MockKvNamespace) RunKvReflection(_param0 api.APIReflectionType, _param1 api.KvQuery) {
	_m.ctrl.Call(_m, "RunKvReflection", _param0, _param1)
}

func (_mr *_MockKvNamespaceRecorder) RunKvReflection(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RunKvReflection", arg0, arg1)
}

// Mock of RemoteStore interface
type MockRemoteStore struct {
	ctrl     *gomock.Controller
	recorder *_MockRemoteStoreRecorder
}

// Recorder for MockRemoteStore (not exported)
type _MockRemoteStoreRecorder struct {
	mock *MockRemoteStore
}

func NewMockRemoteStore(ctrl *gomock.Controller) *MockRemoteStore {
	mock := &MockRemoteStore{ctrl: ctrl}
	mock.recorder = &_MockRemoteStoreRecorder{mock}
	return mock
}

func (_m *MockRemoteStore) EXPECT() *_MockRemoteStoreRecorder {
	return _m.recorder
}

func (_m *MockRemoteStore) AddIndex(_param0 crdt.Index) (crdt.RemoteStoreAddress, error) {
	ret := _m.ctrl.Call(_m, "AddIndex", _param0)
	ret0, _ := ret[0].(crdt.RemoteStoreAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockRemoteStoreRecorder) AddIndex(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddIndex", arg0)
}

func (_m *MockRemoteStore) AddNamespace(_param0 crdt.Namespace) (crdt.RemoteStoreAddress, error) {
	ret := _m.ctrl.Call(_m, "AddNamespace", _param0)
	ret0, _ := ret[0].(crdt.RemoteStoreAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockRemoteStoreRecorder) AddNamespace(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddNamespace", arg0)
}

func (_m *MockRemoteStore) CatIndex(_param0 crdt.RemoteStoreAddress) (crdt.Index, error) {
	ret := _m.ctrl.Call(_m, "CatIndex", _param0)
	ret0, _ := ret[0].(crdt.Index)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockRemoteStoreRecorder) CatIndex(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CatIndex", arg0)
}

func (_m *MockRemoteStore) CatNamespace(_param0 crdt.RemoteStoreAddress) (crdt.Namespace, error) {
	ret := _m.ctrl.Call(_m, "CatNamespace", _param0)
	ret0, _ := ret[0].(crdt.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockRemoteStoreRecorder) CatNamespace(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CatNamespace", arg0)
}

func (_m *MockRemoteStore) Connect() error {
	ret := _m.ctrl.Call(_m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockRemoteStoreRecorder) Connect() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Connect")
}

func (_m *MockRemoteStore) Disconnect() error {
	ret := _m.ctrl.Call(_m, "Disconnect")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockRemoteStoreRecorder) Disconnect() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Disconnect")
}

func (_m *MockRemoteStore) PublishAddr(_param0 crdt.RemoteStoreAddress, _param1 []crdt.RemoteStoreAddress) error {
	ret := _m.ctrl.Call(_m, "PublishAddr", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockRemoteStoreRecorder) PublishAddr(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PublishAddr", arg0, arg1)
}

func (_m *MockRemoteStore) SubscribeAddrStream(_param0 crdt.RemoteStoreAddress) (<-chan crdt.RemoteStoreAddress, <-chan error) {
	ret := _m.ctrl.Call(_m, "SubscribeAddrStream", _param0)
	ret0, _ := ret[0].(<-chan crdt.RemoteStoreAddress)
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

func (_mr *_MockRemoteStoreRecorder) SubscribeAddrStream(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SubscribeAddrStream", arg0)
}

// Mock of NamespaceTree interface
type MockNamespaceTree struct {
	ctrl     *gomock.Controller
	recorder *_MockNamespaceTreeRecorder
}

// Recorder for MockNamespaceTree (not exported)
type _MockNamespaceTreeRecorder struct {
	mock *MockNamespaceTree
}

func NewMockNamespaceTree(ctrl *gomock.Controller) *MockNamespaceTree {
	mock := &MockNamespaceTree{ctrl: ctrl}
	mock.recorder = &_MockNamespaceTreeRecorder{mock}
	return mock
}

func (_m *MockNamespaceTree) EXPECT() *_MockNamespaceTreeRecorder {
	return _m.recorder
}

func (_m *MockNamespaceTree) JoinTable(_param0 crdt.TableName, _param1 crdt.Table) error {
	ret := _m.ctrl.Call(_m, "JoinTable", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockNamespaceTreeRecorder) JoinTable(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "JoinTable", arg0, arg1)
}

func (_m *MockNamespaceTree) LoadTraverse(_param0 api.NamespaceTreeTableReader) error {
	ret := _m.ctrl.Call(_m, "LoadTraverse", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockNamespaceTreeRecorder) LoadTraverse(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LoadTraverse", arg0)
}

// Mock of NamespaceTreeTableReader interface
type MockNamespaceTreeTableReader struct {
	ctrl     *gomock.Controller
	recorder *_MockNamespaceTreeTableReaderRecorder
}

// Recorder for MockNamespaceTreeTableReader (not exported)
type _MockNamespaceTreeTableReaderRecorder struct {
	mock *MockNamespaceTreeTableReader
}

func NewMockNamespaceTreeTableReader(ctrl *gomock.Controller) *MockNamespaceTreeTableReader {
	mock := &MockNamespaceTreeTableReader{ctrl: ctrl}
	mock.recorder = &_MockNamespaceTreeTableReaderRecorder{mock}
	return mock
}

func (_m *MockNamespaceTreeTableReader) EXPECT() *_MockNamespaceTreeTableReaderRecorder {
	return _m.recorder
}

func (_m *MockNamespaceTreeTableReader) ReadNamespace(_param0 crdt.Namespace) (bool, error) {
	ret := _m.ctrl.Call(_m, "ReadNamespace", _param0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockNamespaceTreeTableReaderRecorder) ReadNamespace(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ReadNamespace", arg0)
}

func (_m *MockNamespaceTreeTableReader) ReadsTables() []crdt.TableName {
	ret := _m.ctrl.Call(_m, "ReadsTables")
	ret0, _ := ret[0].([]crdt.TableName)
	return ret0
}

func (_mr *_MockNamespaceTreeTableReaderRecorder) ReadsTables() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ReadsTables")
}
