// Code generated by protoc-gen-go. DO NOT EDIT.
// source: godless.proto

/*
Package godless is a generated protocol buffer package.

It is generated from these files:
	godless.proto

It has these top-level messages:
	NamespaceMessage
	NamespaceEntryMessage
	IndexMessage
	IndexEntryMessage
	APIResponseMessage
	QueryMessage
	QueryJoinMessage
	QueryRowJoinMessage
	QueryRowJoinEntryMessage
	QuerySelectMessage
	QueryWhereMessage
	QueryPredicateMessage
*/
package godless

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NamespaceMessage struct {
	Entries []*NamespaceEntryMessage `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
}

func (m *NamespaceMessage) Reset()                    { *m = NamespaceMessage{} }
func (m *NamespaceMessage) String() string            { return proto.CompactTextString(m) }
func (*NamespaceMessage) ProtoMessage()               {}
func (*NamespaceMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NamespaceMessage) GetEntries() []*NamespaceEntryMessage {
	if m != nil {
		return m.Entries
	}
	return nil
}

type NamespaceEntryMessage struct {
	Table  string   `protobuf:"bytes,1,opt,name=table" json:"table,omitempty"`
	Row    string   `protobuf:"bytes,2,opt,name=row" json:"row,omitempty"`
	Entry  string   `protobuf:"bytes,3,opt,name=entry" json:"entry,omitempty"`
	Points []string `protobuf:"bytes,4,rep,name=points" json:"points,omitempty"`
}

func (m *NamespaceEntryMessage) Reset()                    { *m = NamespaceEntryMessage{} }
func (m *NamespaceEntryMessage) String() string            { return proto.CompactTextString(m) }
func (*NamespaceEntryMessage) ProtoMessage()               {}
func (*NamespaceEntryMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NamespaceEntryMessage) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *NamespaceEntryMessage) GetRow() string {
	if m != nil {
		return m.Row
	}
	return ""
}

func (m *NamespaceEntryMessage) GetEntry() string {
	if m != nil {
		return m.Entry
	}
	return ""
}

func (m *NamespaceEntryMessage) GetPoints() []string {
	if m != nil {
		return m.Points
	}
	return nil
}

type IndexMessage struct {
	Entries []*IndexEntryMessage `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
}

func (m *IndexMessage) Reset()                    { *m = IndexMessage{} }
func (m *IndexMessage) String() string            { return proto.CompactTextString(m) }
func (*IndexMessage) ProtoMessage()               {}
func (*IndexMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IndexMessage) GetEntries() []*IndexEntryMessage {
	if m != nil {
		return m.Entries
	}
	return nil
}

type IndexEntryMessage struct {
	Table string   `protobuf:"bytes,1,opt,name=table" json:"table,omitempty"`
	Links []string `protobuf:"bytes,2,rep,name=links" json:"links,omitempty"`
}

func (m *IndexEntryMessage) Reset()                    { *m = IndexEntryMessage{} }
func (m *IndexEntryMessage) String() string            { return proto.CompactTextString(m) }
func (*IndexEntryMessage) ProtoMessage()               {}
func (*IndexEntryMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IndexEntryMessage) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *IndexEntryMessage) GetLinks() []string {
	if m != nil {
		return m.Links
	}
	return nil
}

type APIResponseMessage struct {
}

func (m *APIResponseMessage) Reset()                    { *m = APIResponseMessage{} }
func (m *APIResponseMessage) String() string            { return proto.CompactTextString(m) }
func (*APIResponseMessage) ProtoMessage()               {}
func (*APIResponseMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type QueryMessage struct {
	OpCode uint32              `protobuf:"varint,1,opt,name=opCode" json:"opCode,omitempty"`
	Table  string              `protobuf:"bytes,2,opt,name=table" json:"table,omitempty"`
	Join   *QueryJoinMessage   `protobuf:"bytes,3,opt,name=join" json:"join,omitempty"`
	Select *QuerySelectMessage `protobuf:"bytes,4,opt,name=select" json:"select,omitempty"`
}

func (m *QueryMessage) Reset()                    { *m = QueryMessage{} }
func (m *QueryMessage) String() string            { return proto.CompactTextString(m) }
func (*QueryMessage) ProtoMessage()               {}
func (*QueryMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *QueryMessage) GetOpCode() uint32 {
	if m != nil {
		return m.OpCode
	}
	return 0
}

func (m *QueryMessage) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *QueryMessage) GetJoin() *QueryJoinMessage {
	if m != nil {
		return m.Join
	}
	return nil
}

func (m *QueryMessage) GetSelect() *QuerySelectMessage {
	if m != nil {
		return m.Select
	}
	return nil
}

type QueryJoinMessage struct {
	Rows []*QueryRowJoinMessage `protobuf:"bytes,1,rep,name=rows" json:"rows,omitempty"`
}

func (m *QueryJoinMessage) Reset()                    { *m = QueryJoinMessage{} }
func (m *QueryJoinMessage) String() string            { return proto.CompactTextString(m) }
func (*QueryJoinMessage) ProtoMessage()               {}
func (*QueryJoinMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *QueryJoinMessage) GetRows() []*QueryRowJoinMessage {
	if m != nil {
		return m.Rows
	}
	return nil
}

type QueryRowJoinMessage struct {
	Row     string                      `protobuf:"bytes,1,opt,name=row" json:"row,omitempty"`
	Entries []*QueryRowJoinEntryMessage `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
}

func (m *QueryRowJoinMessage) Reset()                    { *m = QueryRowJoinMessage{} }
func (m *QueryRowJoinMessage) String() string            { return proto.CompactTextString(m) }
func (*QueryRowJoinMessage) ProtoMessage()               {}
func (*QueryRowJoinMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *QueryRowJoinMessage) GetRow() string {
	if m != nil {
		return m.Row
	}
	return ""
}

func (m *QueryRowJoinMessage) GetEntries() []*QueryRowJoinEntryMessage {
	if m != nil {
		return m.Entries
	}
	return nil
}

type QueryRowJoinEntryMessage struct {
	Entry string `protobuf:"bytes,1,opt,name=entry" json:"entry,omitempty"`
	Point string `protobuf:"bytes,2,opt,name=point" json:"point,omitempty"`
}

func (m *QueryRowJoinEntryMessage) Reset()                    { *m = QueryRowJoinEntryMessage{} }
func (m *QueryRowJoinEntryMessage) String() string            { return proto.CompactTextString(m) }
func (*QueryRowJoinEntryMessage) ProtoMessage()               {}
func (*QueryRowJoinEntryMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *QueryRowJoinEntryMessage) GetEntry() string {
	if m != nil {
		return m.Entry
	}
	return ""
}

func (m *QueryRowJoinEntryMessage) GetPoint() string {
	if m != nil {
		return m.Point
	}
	return ""
}

type QuerySelectMessage struct {
	Limit uint32             `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Where *QueryWhereMessage `protobuf:"bytes,2,opt,name=where" json:"where,omitempty"`
}

func (m *QuerySelectMessage) Reset()                    { *m = QuerySelectMessage{} }
func (m *QuerySelectMessage) String() string            { return proto.CompactTextString(m) }
func (*QuerySelectMessage) ProtoMessage()               {}
func (*QuerySelectMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *QuerySelectMessage) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QuerySelectMessage) GetWhere() *QueryWhereMessage {
	if m != nil {
		return m.Where
	}
	return nil
}

type QueryWhereMessage struct {
	OpCode    uint32                 `protobuf:"varint,1,opt,name=opCode" json:"opCode,omitempty"`
	Predicate *QueryPredicateMessage `protobuf:"bytes,2,opt,name=predicate" json:"predicate,omitempty"`
	Clauses   []*QueryWhereMessage   `protobuf:"bytes,3,rep,name=clauses" json:"clauses,omitempty"`
}

func (m *QueryWhereMessage) Reset()                    { *m = QueryWhereMessage{} }
func (m *QueryWhereMessage) String() string            { return proto.CompactTextString(m) }
func (*QueryWhereMessage) ProtoMessage()               {}
func (*QueryWhereMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *QueryWhereMessage) GetOpCode() uint32 {
	if m != nil {
		return m.OpCode
	}
	return 0
}

func (m *QueryWhereMessage) GetPredicate() *QueryPredicateMessage {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (m *QueryWhereMessage) GetClauses() []*QueryWhereMessage {
	if m != nil {
		return m.Clauses
	}
	return nil
}

type QueryPredicateMessage struct {
	OpCode   uint32   `protobuf:"varint,1,opt,name=opCode" json:"opCode,omitempty"`
	Keys     []string `protobuf:"bytes,2,rep,name=keys" json:"keys,omitempty"`
	Literals []string `protobuf:"bytes,3,rep,name=literals" json:"literals,omitempty"`
	Userow   bool     `protobuf:"varint,4,opt,name=userow" json:"userow,omitempty"`
}

func (m *QueryPredicateMessage) Reset()                    { *m = QueryPredicateMessage{} }
func (m *QueryPredicateMessage) String() string            { return proto.CompactTextString(m) }
func (*QueryPredicateMessage) ProtoMessage()               {}
func (*QueryPredicateMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *QueryPredicateMessage) GetOpCode() uint32 {
	if m != nil {
		return m.OpCode
	}
	return 0
}

func (m *QueryPredicateMessage) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *QueryPredicateMessage) GetLiterals() []string {
	if m != nil {
		return m.Literals
	}
	return nil
}

func (m *QueryPredicateMessage) GetUserow() bool {
	if m != nil {
		return m.Userow
	}
	return false
}

func init() {
	proto.RegisterType((*NamespaceMessage)(nil), "godless.NamespaceMessage")
	proto.RegisterType((*NamespaceEntryMessage)(nil), "godless.NamespaceEntryMessage")
	proto.RegisterType((*IndexMessage)(nil), "godless.IndexMessage")
	proto.RegisterType((*IndexEntryMessage)(nil), "godless.IndexEntryMessage")
	proto.RegisterType((*APIResponseMessage)(nil), "godless.APIResponseMessage")
	proto.RegisterType((*QueryMessage)(nil), "godless.QueryMessage")
	proto.RegisterType((*QueryJoinMessage)(nil), "godless.QueryJoinMessage")
	proto.RegisterType((*QueryRowJoinMessage)(nil), "godless.QueryRowJoinMessage")
	proto.RegisterType((*QueryRowJoinEntryMessage)(nil), "godless.QueryRowJoinEntryMessage")
	proto.RegisterType((*QuerySelectMessage)(nil), "godless.QuerySelectMessage")
	proto.RegisterType((*QueryWhereMessage)(nil), "godless.QueryWhereMessage")
	proto.RegisterType((*QueryPredicateMessage)(nil), "godless.QueryPredicateMessage")
}

func init() { proto.RegisterFile("godless.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0xd5, 0x66, 0x37, 0x69, 0x33, 0x6d, 0xa5, 0xd4, 0xa4, 0x95, 0x29, 0xa8, 0x0a, 0x3e, 0xe5,
	0x42, 0x55, 0xb5, 0x1c, 0x90, 0x40, 0x42, 0x88, 0x82, 0x54, 0x04, 0xa8, 0x2c, 0x07, 0x2e, 0x5c,
	0xb6, 0xd9, 0x51, 0x31, 0xd9, 0xd8, 0x2b, 0xdb, 0xd1, 0x92, 0x5f, 0x03, 0x3f, 0xb5, 0xb2, 0xbd,
	0xce, 0xe6, 0x63, 0x73, 0xdb, 0x97, 0x79, 0xf3, 0x66, 0x3c, 0xef, 0x29, 0x70, 0xf4, 0x20, 0xf3,
	0x02, 0xb5, 0xbe, 0x28, 0x95, 0x34, 0x92, 0xec, 0xd5, 0x90, 0x7d, 0x81, 0xc1, 0xb7, 0x6c, 0x86,
	0xba, 0xcc, 0x26, 0xf8, 0x15, 0xb5, 0xce, 0x1e, 0x90, 0xbc, 0x86, 0x3d, 0x14, 0x46, 0x71, 0xd4,
	0x34, 0x1a, 0xc5, 0xe3, 0x83, 0xab, 0xf3, 0x8b, 0xd0, 0xbd, 0xe4, 0x7e, 0x14, 0x46, 0x2d, 0xea,
	0x86, 0x34, 0xd0, 0xd9, 0x0c, 0x4e, 0x5a, 0x19, 0x64, 0x08, 0x5d, 0x93, 0xdd, 0x17, 0x48, 0xa3,
	0x51, 0x34, 0xee, 0xa7, 0x1e, 0x90, 0x01, 0xc4, 0x4a, 0x56, 0xb4, 0xe3, 0x7e, 0xb3, 0x9f, 0x96,
	0x67, 0xb5, 0x16, 0x34, 0xf6, 0x3c, 0x07, 0xc8, 0x29, 0xf4, 0x4a, 0xc9, 0x85, 0xd1, 0x34, 0x19,
	0xc5, 0xe3, 0x7e, 0x5a, 0x23, 0x76, 0x03, 0x87, 0xb7, 0x22, 0xc7, 0xbf, 0x61, 0xca, 0xab, 0xcd,
	0xc5, 0xcf, 0x96, 0x8b, 0x3b, 0x5e, 0xfb, 0xd2, 0xef, 0xe0, 0x78, 0xab, 0xba, 0x63, 0xe1, 0x21,
	0x74, 0x0b, 0x2e, 0xa6, 0x9a, 0x76, 0xdc, 0x1e, 0x1e, 0xb0, 0x21, 0x90, 0xf7, 0x77, 0xb7, 0x29,
	0xea, 0x52, 0x0a, 0x1d, 0xae, 0xc8, 0xfe, 0x47, 0x70, 0xf8, 0x7d, 0x8e, 0x8d, 0xe4, 0x29, 0xf4,
	0x64, 0xf9, 0x41, 0xe6, 0x5e, 0xf3, 0x28, 0xad, 0x51, 0x33, 0xaa, 0xb3, 0x3a, 0xea, 0x25, 0x24,
	0x7f, 0x24, 0x17, 0xee, 0x10, 0x07, 0x57, 0x4f, 0x97, 0x0f, 0x71, 0x92, 0x9f, 0x25, 0x17, 0xe1,
	0x1d, 0x8e, 0x46, 0xae, 0xa1, 0xa7, 0xb1, 0xc0, 0x89, 0xa1, 0x89, 0x6b, 0x78, 0xb6, 0xde, 0xf0,
	0xc3, 0xd5, 0x42, 0x4b, 0x4d, 0x65, 0x37, 0x30, 0xd8, 0x94, 0x23, 0x97, 0x90, 0x28, 0x59, 0x85,
	0x03, 0x3e, 0x5f, 0x97, 0x49, 0x65, 0xb5, 0x36, 0xda, 0x32, 0x59, 0x0e, 0x4f, 0x5a, 0x8a, 0xc1,
	0xdc, 0xa8, 0x31, 0xf7, 0x4d, 0x63, 0x4f, 0xc7, 0xa9, 0xbf, 0x68, 0x55, 0x6f, 0x77, 0xe9, 0x13,
	0xd0, 0x5d, 0xa4, 0x26, 0x35, 0xd1, 0x6a, 0x6a, 0x86, 0xd0, 0x75, 0x39, 0x09, 0x77, 0x75, 0x80,
	0xfd, 0x02, 0xb2, 0x7d, 0x11, 0x6f, 0xec, 0x8c, 0x9b, 0xda, 0x1a, 0x0f, 0xc8, 0x25, 0x74, 0xab,
	0xdf, 0xa8, 0xbc, 0x33, 0xab, 0x69, 0x72, 0x0a, 0x3f, 0x6d, 0x29, 0xec, 0xe9, 0x89, 0xec, 0x5f,
	0x04, 0xc7, 0x5b, 0xc5, 0x9d, 0xce, 0xbf, 0x85, 0x7e, 0xa9, 0x30, 0xe7, 0x93, 0xcc, 0x84, 0x19,
	0xe7, 0xeb, 0x33, 0xee, 0x42, 0x39, 0xcc, 0x69, 0x1a, 0x6c, 0xda, 0x27, 0x45, 0x36, 0xd7, 0xa8,
	0x69, 0xbc, 0x91, 0xf6, 0xed, 0xfd, 0x02, 0x95, 0x55, 0x70, 0xd2, 0xaa, 0xbc, 0x73, 0x49, 0x02,
	0xc9, 0x14, 0x17, 0x21, 0xf2, 0xee, 0x9b, 0x9c, 0xc1, 0x7e, 0xc1, 0x0d, 0xaa, 0xac, 0xf0, 0xb3,
	0xfb, 0xe9, 0x12, 0x5b, 0x9d, 0xb9, 0x46, 0x6b, 0xbd, 0x4d, 0xe2, 0x7e, 0x5a, 0xa3, 0xfb, 0x9e,
	0xfb, 0xe7, 0xb9, 0x7e, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xde, 0xd5, 0xe2, 0x8a, 0x04, 0x00,
	0x00,
}
