// Code generated by protoc-gen-go. DO NOT EDIT.
// source: godless.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	godless.proto

It has these top-level messages:
	NamespaceMessage
	NamespaceEntryMessage
	PointMessage
	IndexMessage
	IndexEntryMessage
	LinkMessage
	APIRequestMessage
	ReplicateMessage
	APIResponseMessage
	QueryMessage
	QueryJoinMessage
	QueryRowJoinMessage
	QueryRowJoinEntryMessage
	QuerySelectMessage
	QueryWhereMessage
	QueryPredicateMessage
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type NamespaceMessage struct {
	Entries []*NamespaceEntryMessage `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
}

func (m *NamespaceMessage) Reset()                    { *m = NamespaceMessage{} }
func (m *NamespaceMessage) String() string            { return proto1.CompactTextString(m) }
func (*NamespaceMessage) ProtoMessage()               {}
func (*NamespaceMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NamespaceMessage) GetEntries() []*NamespaceEntryMessage {
	if m != nil {
		return m.Entries
	}
	return nil
}

type NamespaceEntryMessage struct {
	Table string        `protobuf:"bytes,1,opt,name=table" json:"table,omitempty"`
	Row   string        `protobuf:"bytes,2,opt,name=row" json:"row,omitempty"`
	Entry string        `protobuf:"bytes,3,opt,name=entry" json:"entry,omitempty"`
	Point *PointMessage `protobuf:"bytes,4,opt,name=point" json:"point,omitempty"`
}

func (m *NamespaceEntryMessage) Reset()                    { *m = NamespaceEntryMessage{} }
func (m *NamespaceEntryMessage) String() string            { return proto1.CompactTextString(m) }
func (*NamespaceEntryMessage) ProtoMessage()               {}
func (*NamespaceEntryMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NamespaceEntryMessage) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *NamespaceEntryMessage) GetRow() string {
	if m != nil {
		return m.Row
	}
	return ""
}

func (m *NamespaceEntryMessage) GetEntry() string {
	if m != nil {
		return m.Entry
	}
	return ""
}

func (m *NamespaceEntryMessage) GetPoint() *PointMessage {
	if m != nil {
		return m.Point
	}
	return nil
}

type PointMessage struct {
	Text      string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Signature string `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
}

func (m *PointMessage) Reset()                    { *m = PointMessage{} }
func (m *PointMessage) String() string            { return proto1.CompactTextString(m) }
func (*PointMessage) ProtoMessage()               {}
func (*PointMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PointMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PointMessage) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type IndexMessage struct {
	Entries []*IndexEntryMessage `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
}

func (m *IndexMessage) Reset()                    { *m = IndexMessage{} }
func (m *IndexMessage) String() string            { return proto1.CompactTextString(m) }
func (*IndexMessage) ProtoMessage()               {}
func (*IndexMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IndexMessage) GetEntries() []*IndexEntryMessage {
	if m != nil {
		return m.Entries
	}
	return nil
}

type IndexEntryMessage struct {
	Table     string `protobuf:"bytes,1,opt,name=table" json:"table,omitempty"`
	Link      string `protobuf:"bytes,2,opt,name=link" json:"link,omitempty"`
	Signature string `protobuf:"bytes,3,opt,name=signature" json:"signature,omitempty"`
}

func (m *IndexEntryMessage) Reset()                    { *m = IndexEntryMessage{} }
func (m *IndexEntryMessage) String() string            { return proto1.CompactTextString(m) }
func (*IndexEntryMessage) ProtoMessage()               {}
func (*IndexEntryMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IndexEntryMessage) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *IndexEntryMessage) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *IndexEntryMessage) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type LinkMessage struct {
	Link       string   `protobuf:"bytes,1,opt,name=link" json:"link,omitempty"`
	Signatures []string `protobuf:"bytes,2,rep,name=signatures" json:"signatures,omitempty"`
}

func (m *LinkMessage) Reset()                    { *m = LinkMessage{} }
func (m *LinkMessage) String() string            { return proto1.CompactTextString(m) }
func (*LinkMessage) ProtoMessage()               {}
func (*LinkMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LinkMessage) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *LinkMessage) GetSignatures() []string {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type APIRequestMessage struct {
	Type       uint32            `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Reflection uint32            `protobuf:"varint,2,opt,name=reflection" json:"reflection,omitempty"`
	Query      *QueryMessage     `protobuf:"bytes,3,opt,name=query" json:"query,omitempty"`
	Replicate  *ReplicateMessage `protobuf:"bytes,4,opt,name=replicate" json:"replicate,omitempty"`
}

func (m *APIRequestMessage) Reset()                    { *m = APIRequestMessage{} }
func (m *APIRequestMessage) String() string            { return proto1.CompactTextString(m) }
func (*APIRequestMessage) ProtoMessage()               {}
func (*APIRequestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *APIRequestMessage) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *APIRequestMessage) GetReflection() uint32 {
	if m != nil {
		return m.Reflection
	}
	return 0
}

func (m *APIRequestMessage) GetQuery() *QueryMessage {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *APIRequestMessage) GetReplicate() *ReplicateMessage {
	if m != nil {
		return m.Replicate
	}
	return nil
}

type ReplicateMessage struct {
	Links []*LinkMessage `protobuf:"bytes,1,rep,name=links" json:"links,omitempty"`
}

func (m *ReplicateMessage) Reset()                    { *m = ReplicateMessage{} }
func (m *ReplicateMessage) String() string            { return proto1.CompactTextString(m) }
func (*ReplicateMessage) ProtoMessage()               {}
func (*ReplicateMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReplicateMessage) GetLinks() []*LinkMessage {
	if m != nil {
		return m.Links
	}
	return nil
}

type APIResponseMessage struct {
	Message   string            `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Error     string            `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Type      uint32            `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Path      string            `protobuf:"bytes,4,opt,name=path" json:"path,omitempty"`
	Namespace *NamespaceMessage `protobuf:"bytes,5,opt,name=namespace" json:"namespace,omitempty"`
	Index     *IndexMessage     `protobuf:"bytes,6,opt,name=index" json:"index,omitempty"`
}

func (m *APIResponseMessage) Reset()                    { *m = APIResponseMessage{} }
func (m *APIResponseMessage) String() string            { return proto1.CompactTextString(m) }
func (*APIResponseMessage) ProtoMessage()               {}
func (*APIResponseMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *APIResponseMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *APIResponseMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *APIResponseMessage) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *APIResponseMessage) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *APIResponseMessage) GetNamespace() *NamespaceMessage {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *APIResponseMessage) GetIndex() *IndexMessage {
	if m != nil {
		return m.Index
	}
	return nil
}

type QueryMessage struct {
	OpCode    uint32              `protobuf:"varint,1,opt,name=opCode" json:"opCode,omitempty"`
	Table     string              `protobuf:"bytes,2,opt,name=table" json:"table,omitempty"`
	Join      *QueryJoinMessage   `protobuf:"bytes,3,opt,name=join" json:"join,omitempty"`
	Select    *QuerySelectMessage `protobuf:"bytes,4,opt,name=select" json:"select,omitempty"`
	KeyHashes []string            `protobuf:"bytes,5,rep,name=keyHashes" json:"keyHashes,omitempty"`
}

func (m *QueryMessage) Reset()                    { *m = QueryMessage{} }
func (m *QueryMessage) String() string            { return proto1.CompactTextString(m) }
func (*QueryMessage) ProtoMessage()               {}
func (*QueryMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *QueryMessage) GetOpCode() uint32 {
	if m != nil {
		return m.OpCode
	}
	return 0
}

func (m *QueryMessage) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *QueryMessage) GetJoin() *QueryJoinMessage {
	if m != nil {
		return m.Join
	}
	return nil
}

func (m *QueryMessage) GetSelect() *QuerySelectMessage {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *QueryMessage) GetKeyHashes() []string {
	if m != nil {
		return m.KeyHashes
	}
	return nil
}

type QueryJoinMessage struct {
	Rows []*QueryRowJoinMessage `protobuf:"bytes,1,rep,name=rows" json:"rows,omitempty"`
}

func (m *QueryJoinMessage) Reset()                    { *m = QueryJoinMessage{} }
func (m *QueryJoinMessage) String() string            { return proto1.CompactTextString(m) }
func (*QueryJoinMessage) ProtoMessage()               {}
func (*QueryJoinMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *QueryJoinMessage) GetRows() []*QueryRowJoinMessage {
	if m != nil {
		return m.Rows
	}
	return nil
}

type QueryRowJoinMessage struct {
	Row     string                      `protobuf:"bytes,1,opt,name=row" json:"row,omitempty"`
	Entries []*QueryRowJoinEntryMessage `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
}

func (m *QueryRowJoinMessage) Reset()                    { *m = QueryRowJoinMessage{} }
func (m *QueryRowJoinMessage) String() string            { return proto1.CompactTextString(m) }
func (*QueryRowJoinMessage) ProtoMessage()               {}
func (*QueryRowJoinMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *QueryRowJoinMessage) GetRow() string {
	if m != nil {
		return m.Row
	}
	return ""
}

func (m *QueryRowJoinMessage) GetEntries() []*QueryRowJoinEntryMessage {
	if m != nil {
		return m.Entries
	}
	return nil
}

type QueryRowJoinEntryMessage struct {
	Entry string `protobuf:"bytes,1,opt,name=entry" json:"entry,omitempty"`
	Point string `protobuf:"bytes,2,opt,name=point" json:"point,omitempty"`
}

func (m *QueryRowJoinEntryMessage) Reset()                    { *m = QueryRowJoinEntryMessage{} }
func (m *QueryRowJoinEntryMessage) String() string            { return proto1.CompactTextString(m) }
func (*QueryRowJoinEntryMessage) ProtoMessage()               {}
func (*QueryRowJoinEntryMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *QueryRowJoinEntryMessage) GetEntry() string {
	if m != nil {
		return m.Entry
	}
	return ""
}

func (m *QueryRowJoinEntryMessage) GetPoint() string {
	if m != nil {
		return m.Point
	}
	return ""
}

type QuerySelectMessage struct {
	Limit uint32             `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Where *QueryWhereMessage `protobuf:"bytes,2,opt,name=where" json:"where,omitempty"`
}

func (m *QuerySelectMessage) Reset()                    { *m = QuerySelectMessage{} }
func (m *QuerySelectMessage) String() string            { return proto1.CompactTextString(m) }
func (*QuerySelectMessage) ProtoMessage()               {}
func (*QuerySelectMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *QuerySelectMessage) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QuerySelectMessage) GetWhere() *QueryWhereMessage {
	if m != nil {
		return m.Where
	}
	return nil
}

type QueryWhereMessage struct {
	OpCode    uint32                 `protobuf:"varint,1,opt,name=opCode" json:"opCode,omitempty"`
	Predicate *QueryPredicateMessage `protobuf:"bytes,2,opt,name=predicate" json:"predicate,omitempty"`
	Clauses   []*QueryWhereMessage   `protobuf:"bytes,3,rep,name=clauses" json:"clauses,omitempty"`
}

func (m *QueryWhereMessage) Reset()                    { *m = QueryWhereMessage{} }
func (m *QueryWhereMessage) String() string            { return proto1.CompactTextString(m) }
func (*QueryWhereMessage) ProtoMessage()               {}
func (*QueryWhereMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *QueryWhereMessage) GetOpCode() uint32 {
	if m != nil {
		return m.OpCode
	}
	return 0
}

func (m *QueryWhereMessage) GetPredicate() *QueryPredicateMessage {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (m *QueryWhereMessage) GetClauses() []*QueryWhereMessage {
	if m != nil {
		return m.Clauses
	}
	return nil
}

type QueryPredicateMessage struct {
	OpCode   uint32   `protobuf:"varint,1,opt,name=opCode" json:"opCode,omitempty"`
	Keys     []string `protobuf:"bytes,2,rep,name=keys" json:"keys,omitempty"`
	Literals []string `protobuf:"bytes,3,rep,name=literals" json:"literals,omitempty"`
	Userow   bool     `protobuf:"varint,4,opt,name=userow" json:"userow,omitempty"`
}

func (m *QueryPredicateMessage) Reset()                    { *m = QueryPredicateMessage{} }
func (m *QueryPredicateMessage) String() string            { return proto1.CompactTextString(m) }
func (*QueryPredicateMessage) ProtoMessage()               {}
func (*QueryPredicateMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *QueryPredicateMessage) GetOpCode() uint32 {
	if m != nil {
		return m.OpCode
	}
	return 0
}

func (m *QueryPredicateMessage) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *QueryPredicateMessage) GetLiterals() []string {
	if m != nil {
		return m.Literals
	}
	return nil
}

func (m *QueryPredicateMessage) GetUserow() bool {
	if m != nil {
		return m.Userow
	}
	return false
}

func init() {
	proto1.RegisterType((*NamespaceMessage)(nil), "proto.NamespaceMessage")
	proto1.RegisterType((*NamespaceEntryMessage)(nil), "proto.NamespaceEntryMessage")
	proto1.RegisterType((*PointMessage)(nil), "proto.PointMessage")
	proto1.RegisterType((*IndexMessage)(nil), "proto.IndexMessage")
	proto1.RegisterType((*IndexEntryMessage)(nil), "proto.IndexEntryMessage")
	proto1.RegisterType((*LinkMessage)(nil), "proto.LinkMessage")
	proto1.RegisterType((*APIRequestMessage)(nil), "proto.APIRequestMessage")
	proto1.RegisterType((*ReplicateMessage)(nil), "proto.ReplicateMessage")
	proto1.RegisterType((*APIResponseMessage)(nil), "proto.APIResponseMessage")
	proto1.RegisterType((*QueryMessage)(nil), "proto.QueryMessage")
	proto1.RegisterType((*QueryJoinMessage)(nil), "proto.QueryJoinMessage")
	proto1.RegisterType((*QueryRowJoinMessage)(nil), "proto.QueryRowJoinMessage")
	proto1.RegisterType((*QueryRowJoinEntryMessage)(nil), "proto.QueryRowJoinEntryMessage")
	proto1.RegisterType((*QuerySelectMessage)(nil), "proto.QuerySelectMessage")
	proto1.RegisterType((*QueryWhereMessage)(nil), "proto.QueryWhereMessage")
	proto1.RegisterType((*QueryPredicateMessage)(nil), "proto.QueryPredicateMessage")
}

func init() { proto1.RegisterFile("godless.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 702 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x63, 0x3b, 0xad, 0xa7, 0xad, 0x94, 0x6e, 0x5b, 0x6a, 0xaa, 0x0a, 0x22, 0x9f, 0x82,
	0x90, 0x22, 0x51, 0x04, 0x12, 0x88, 0x03, 0x2d, 0x02, 0xd1, 0x0a, 0x50, 0x59, 0x0e, 0x48, 0x70,
	0x72, 0x93, 0xa1, 0x35, 0x71, 0xbc, 0xae, 0x77, 0xa3, 0x34, 0x37, 0xde, 0x83, 0x27, 0xe0, 0x15,
	0x78, 0x08, 0x9e, 0x09, 0xed, 0x9f, 0xbd, 0xf9, 0x3b, 0x79, 0x67, 0xe6, 0xf3, 0xcc, 0xec, 0xf7,
	0xcd, 0x0e, 0xec, 0x5c, 0xb3, 0x61, 0x8e, 0x9c, 0xf7, 0xcb, 0x8a, 0x09, 0x46, 0x42, 0xf5, 0x49,
	0x2e, 0xa0, 0xf3, 0x29, 0x1d, 0x23, 0x2f, 0xd3, 0x01, 0x7e, 0x44, 0xce, 0xd3, 0x6b, 0x24, 0xcf,
	0x61, 0x03, 0x0b, 0x51, 0x65, 0xc8, 0x63, 0xaf, 0xeb, 0xf7, 0xb6, 0x4e, 0x8e, 0xf5, 0x3f, 0xfd,
	0x1a, 0xf9, 0xb6, 0x10, 0xd5, 0xcc, 0xc0, 0xa9, 0x05, 0x27, 0xbf, 0x3c, 0x38, 0x58, 0x09, 0x21,
	0xfb, 0x10, 0x8a, 0xf4, 0x2a, 0xc7, 0xd8, 0xeb, 0x7a, 0xbd, 0x88, 0x6a, 0x83, 0x74, 0xc0, 0xaf,
	0xd8, 0x34, 0x6e, 0x29, 0x9f, 0x3c, 0x4a, 0x9c, 0x4c, 0x36, 0x8b, 0x7d, 0x8d, 0x53, 0x06, 0x79,
	0x04, 0x61, 0xc9, 0xb2, 0x42, 0xc4, 0x41, 0xd7, 0xeb, 0x6d, 0x9d, 0xec, 0x99, 0x6e, 0x2e, 0xa5,
	0xcf, 0x36, 0xa1, 0x11, 0xc9, 0x6b, 0xd8, 0x76, 0xdd, 0x84, 0x40, 0x20, 0xf0, 0x4e, 0x98, 0xba,
	0xea, 0x4c, 0x8e, 0x21, 0xe2, 0xd9, 0x75, 0x91, 0x8a, 0x49, 0x85, 0xa6, 0x78, 0xe3, 0x48, 0xce,
	0x60, 0xfb, 0xbc, 0x18, 0xe2, 0x9d, 0xcd, 0x70, 0xb2, 0x48, 0x46, 0x6c, 0xca, 0x2b, 0xd4, 0x6a,
	0x22, 0xbe, 0xc3, 0xee, 0x52, 0x74, 0x0d, 0x07, 0x04, 0x82, 0x3c, 0x2b, 0x46, 0xa6, 0x0f, 0x75,
	0x9e, 0x6f, 0xd0, 0x5f, 0x6c, 0xf0, 0x14, 0xb6, 0x3e, 0x64, 0xc5, 0xc8, 0xb9, 0xa1, 0x4a, 0xe0,
	0x39, 0x09, 0x1e, 0x00, 0xd4, 0x78, 0x1e, 0xb7, 0xba, 0x7e, 0x2f, 0xa2, 0x8e, 0x27, 0xf9, 0xe3,
	0xc1, 0xee, 0xe9, 0xe5, 0x39, 0xc5, 0xdb, 0x09, 0xf2, 0x39, 0xae, 0x66, 0xa5, 0xee, 0x6f, 0x87,
	0xaa, 0xb3, 0xcc, 0x54, 0xe1, 0x8f, 0x1c, 0x07, 0x22, 0x63, 0x85, 0x6a, 0x72, 0x87, 0x3a, 0x1e,
	0x29, 0xcd, 0xed, 0x04, 0x8d, 0x60, 0x8d, 0x34, 0x9f, 0xa5, 0xaf, 0x96, 0x46, 0x21, 0xc8, 0x33,
	0x88, 0x2a, 0x2c, 0xf3, 0x6c, 0x90, 0x0a, 0x34, 0x4a, 0x1e, 0x1a, 0x38, 0xb5, 0x7e, 0xfb, 0x4b,
	0x83, 0x4c, 0x5e, 0x41, 0x67, 0x31, 0x4c, 0x7a, 0x10, 0xca, 0x7b, 0x5a, 0x45, 0x88, 0x49, 0xe3,
	0xd0, 0x42, 0x35, 0x20, 0xf9, 0xe7, 0x01, 0x51, 0x37, 0xe5, 0x25, 0x2b, 0x78, 0x9d, 0x20, 0x86,
	0x8d, 0xb1, 0x3e, 0x1a, 0xde, 0xac, 0xa9, 0x26, 0xb0, 0xaa, 0x58, 0x65, 0x04, 0xd1, 0x46, 0x4d,
	0x8d, 0xef, 0x50, 0x43, 0x20, 0x28, 0x53, 0x71, 0xa3, 0xae, 0x12, 0x51, 0x75, 0x96, 0x77, 0x2c,
	0xec, 0x03, 0x88, 0xc3, 0xb9, 0x3b, 0x2e, 0xbe, 0x32, 0xda, 0x20, 0x25, 0x8b, 0x99, 0x9c, 0x97,
	0xb8, 0x3d, 0xc7, 0xa2, 0x3b, 0x87, 0x54, 0x23, 0x92, 0xbf, 0x1e, 0x6c, 0xbb, 0xec, 0x92, 0x7b,
	0xd0, 0x66, 0xe5, 0x1b, 0x36, 0xb4, 0xba, 0x19, 0xab, 0x19, 0xb7, 0x96, 0x3b, 0x6e, 0x8f, 0x21,
	0xf8, 0xc9, 0xb2, 0xc2, 0xc8, 0x75, 0xe8, 0xca, 0x75, 0xc1, 0xb2, 0xc2, 0x16, 0x53, 0x20, 0xf2,
	0x04, 0xda, 0x1c, 0xa5, 0xd2, 0x46, 0xae, 0xfb, 0x2e, 0xfc, 0x8b, 0x8a, 0xd8, 0x1f, 0x0c, 0x50,
	0x8e, 0xee, 0x08, 0x67, 0xef, 0x53, 0x7e, 0x83, 0x3c, 0x0e, 0xd5, 0xe0, 0x35, 0x8e, 0xe4, 0x0c,
	0x3a, 0x8b, 0xa5, 0x48, 0x1f, 0x82, 0x8a, 0x4d, 0xad, 0x94, 0x47, 0x6e, 0x09, 0xca, 0xa6, 0x73,
	0x4d, 0x49, 0x5c, 0x72, 0x05, 0x7b, 0x2b, 0x82, 0x76, 0x97, 0x78, 0xcd, 0x2e, 0x79, 0xd1, 0x3c,
	0xdc, 0x96, 0xca, 0xfd, 0x70, 0x45, 0xee, 0xd5, 0xef, 0xf7, 0x1d, 0xc4, 0xeb, 0x40, 0xcd, 0x8a,
	0xf2, 0xdc, 0x15, 0xb5, 0x6f, 0x57, 0x94, 0x61, 0x5b, 0x6f, 0xa3, 0x6f, 0x40, 0x96, 0xb9, 0x92,
	0xd8, 0x3c, 0x1b, 0x67, 0xc2, 0x08, 0xa6, 0x0d, 0xd2, 0x87, 0x70, 0x7a, 0x83, 0x66, 0x23, 0x35,
	0x5b, 0x46, 0xfd, 0xff, 0x55, 0x06, 0xea, 0x41, 0x50, 0xb0, 0xe4, 0xb7, 0x07, 0xbb, 0x4b, 0xc1,
	0xb5, 0xd3, 0xf0, 0x12, 0xa2, 0xb2, 0xc2, 0xa1, 0x7e, 0x7c, 0xba, 0xc2, 0xb1, 0x5b, 0xe1, 0xd2,
	0x06, 0xeb, 0xe9, 0xac, 0xe1, 0x72, 0x03, 0x0e, 0xf2, 0x74, 0xc2, 0x91, 0xc7, 0xfe, 0xdc, 0x06,
	0x5c, 0xee, 0xcd, 0x02, 0x93, 0x29, 0x1c, 0xac, 0xcc, 0xbb, 0xb6, 0x41, 0x02, 0xc1, 0x08, 0x67,
	0x76, 0x59, 0xa9, 0x33, 0x39, 0x82, 0xcd, 0x3c, 0x13, 0x58, 0xa5, 0xb9, 0xae, 0x1c, 0xd1, 0xda,
	0x96, 0x79, 0x26, 0x1c, 0xa5, 0xe4, 0x72, 0x36, 0x37, 0xa9, 0xb1, 0xae, 0xda, 0xaa, 0xb5, 0xa7,
	0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xc9, 0x83, 0x0d, 0xee, 0x06, 0x00, 0x00,
}
